global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    product: medkernel
    environment: docker-dev

rule_files:
  - /etc/prometheus/rules/medkernel-alert-rules.yml

scrape_configs:
  - job_name: medkernel-backend
    scrape_interval: 15s
    scrape_timeout: 5s
    metrics_path: /medkernel/actuator/prometheus
    scheme: http
    static_configs:
      - targets:
          - backend:18080
        labels:
          service: medkernel-mvp
          role: backend
