-- AI 知识生产任务表：记录 AI 知识生产流水线的任务状态
CREATE TABLE IF NOT EXISTS ai_knowledge_job (
  id BIGINT PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  job_code VARCHAR(64) NOT NULL,
  job_name VARCHAR(200) NOT NULL,
  job_type VARCHAR(32) NOT NULL,
  source_code VARCHAR(64),
  subscription_id VARCHAR(64),
  model_provider VARCHAR(64),
  model_name VARCHAR(128),
  prompt_version VARCHAR(32),
  input_hash VARCHAR(128),
  output_hash VARCHAR(128),
  input_summary VARCHAR(2000),
  output_summary VARCHAR(2000),
  evidence_ids VARCHAR(1000),
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  review_status VARCHAR(32) DEFAULT 'PENDING',
  reviewed_by VARCHAR(64),
  reviewed_time TIMESTAMP,
  review_comment VARCHAR(2000),
  error_code VARCHAR(64),
  error_message VARCHAR(2000),
  retry_count INTEGER DEFAULT 0 NOT NULL,
  max_retries INTEGER DEFAULT 3 NOT NULL,
  started_time TIMESTAMP,
  finished_time TIMESTAMP,
  duration_ms INTEGER,
  created_by VARCHAR(64),
  created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_by VARCHAR(64),
  updated_time TIMESTAMP,
  CONSTRAINT uk_ai_knowledge_job UNIQUE (tenant_id, job_code)
);

-- AI 模型调用日志表：记录每次模型调用的详细信息
CREATE TABLE IF NOT EXISTS ai_model_call_log (
  id BIGINT PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  job_id BIGINT,
  call_type VARCHAR(32) NOT NULL,
  model_provider VARCHAR(64) NOT NULL,
  model_name VARCHAR(128) NOT NULL,
  model_version VARCHAR(32),
  prompt_template_id VARCHAR(64),
  prompt_version VARCHAR(32),
  prompt_hash VARCHAR(128),
  input_hash VARCHAR(128),
  output_hash VARCHAR(128),
  input_token_count INTEGER,
  output_token_count INTEGER,
  total_token_count INTEGER,
  call_status VARCHAR(32) NOT NULL,
  error_code VARCHAR(64),
  error_message VARCHAR(2000),
  fallback_used VARCHAR(32),
  fallback_provider VARCHAR(64),
  fallback_model VARCHAR(128),
  trace_id VARCHAR(64),
  patient_id VARCHAR(64),
  encounter_id VARCHAR(64),
  elapsed_ms INTEGER,
  called_time TIMESTAMP NOT NULL,
  created_by VARCHAR(64),
  created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
