export const antTheme = {
  token: {
    colorPrimary: "#168bd3",
    colorSuccess: "#12966e",
    colorWarning: "#c78200",
    colorError: "#d33f49",
    colorInfo: "#168bd3",
    colorBgContainer: "#ffffff",
    colorBgLayout: "#f5fbff",
    colorBgElevated: "#ffffff",
    colorBorder: "#d8e8f3",
    colorBorderSecondary: "#ebf2f8",
    colorText: "#1f2d3d",
    colorTextSecondary: "#52677a",
    colorTextTertiary: "#7c8b99",
    colorTextQuaternary: "#7c8b99",
    borderRadius: 6,
    borderRadiusSM: 4,
    borderRadiusLG: 8,
    fontFamily: '-apple-system, BlinkMacSystemFont, "PingFang SC", "Microsoft YaHei", "Source Han Sans CN", sans-serif',
    fontSize: 14,
    fontSizeSM: 13,
    fontSizeLG: 16,
    fontSizeXL: 18,
    controlHeight: 32,
    controlHeightSM: 28,
    controlHeightLG: 40,
    wireframe: false,
  },
  components: {
    Layout: {
      siderBg: "#2fa7e8",
      headerBg: "#ffffff",
      headerPadding: "0 24px",
    },
    Menu: {
      darkItemBg: "#2fa7e8",
      darkItemHoverBg: "#178fd0",
      darkItemSelectedBg: "#0b78bd",
      darkItemColor: "#ffffff",
      darkItemHoverColor: "#ffffff",
    },
  },
};
