-- MedKernel v1.0 GA · GA-ENG-API-09 随访 API（Oracle）

CREATE TABLE followup_plan (
    id                        NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id                   VARCHAR2(64)  NOT NULL,
    tenant_id                 VARCHAR2(64)  NOT NULL,
    patient_id                VARCHAR2(64)  NOT NULL,
    encounter_id              VARCHAR2(64),
    pathway_id                VARCHAR2(64),
    disease_code              VARCHAR2(128),
    risk_level                VARCHAR2(32),
    status                    VARCHAR2(32)  DEFAULT 'DRAFT' NOT NULL,
    created_at                TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by                VARCHAR2(64)  DEFAULT 'system' NOT NULL,
    updated_at                TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by                VARCHAR2(64)  DEFAULT 'system' NOT NULL,
    trace_id                  VARCHAR2(128),
    CONSTRAINT uk_followup_plan_id UNIQUE (plan_id)
);

CREATE INDEX idx_followup_plan_tenant_patient ON followup_plan (tenant_id, patient_id);
CREATE INDEX idx_followup_plan_status ON followup_plan (status);

CREATE TABLE followup_task (
    id                        NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id                   VARCHAR2(64)  NOT NULL,
    tenant_id                 VARCHAR2(64)  NOT NULL,
    plan_id                   VARCHAR2(64)  NOT NULL,
    task_type                 VARCHAR2(32)  NOT NULL,
    due_date                  TIMESTAMP     NOT NULL,
    status                    VARCHAR2(32)  DEFAULT 'PENDING' NOT NULL,
    executor_id               VARCHAR2(64),
    executor_type             VARCHAR2(32),
    created_at                TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by                VARCHAR2(64)  DEFAULT 'system' NOT NULL,
    updated_at                TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by                VARCHAR2(64)  DEFAULT 'system' NOT NULL,
    trace_id                  VARCHAR2(128),
    CONSTRAINT uk_followup_task_id UNIQUE (task_id)
);

CREATE INDEX idx_followup_task_tenant_plan ON followup_task (tenant_id, plan_id);
CREATE INDEX idx_followup_task_due_date ON followup_task (due_date);

CREATE TABLE followup_questionnaire (
    id                        NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    questionnaire_id          VARCHAR2(64)  NOT NULL,
    tenant_id                 VARCHAR2(64)  NOT NULL,
    task_id                   VARCHAR2(64)  NOT NULL,
    form_data                 CLOB          NOT NULL,
    score                     NUMBER(10,2),
    status                    VARCHAR2(32)  DEFAULT 'DRAFT' NOT NULL,
    created_at                TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by                VARCHAR2(64)  DEFAULT 'system' NOT NULL,
    updated_at                TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by                VARCHAR2(64)  DEFAULT 'system' NOT NULL,
    trace_id                  VARCHAR2(128),
    CONSTRAINT uk_followup_questionnaire_id UNIQUE (questionnaire_id)
);

CREATE INDEX idx_followup_questionnaire_task ON followup_questionnaire (tenant_id, task_id);

CREATE TABLE followup_event (
    id                        NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id                  VARCHAR2(64)  NOT NULL,
    tenant_id                 VARCHAR2(64)  NOT NULL,
    plan_id                   VARCHAR2(64),
    event_type                VARCHAR2(32)  NOT NULL,
    payload                   CLOB          NOT NULL,
    triggered_by              VARCHAR2(64),
    created_at                TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by                VARCHAR2(64)  DEFAULT 'system' NOT NULL,
    updated_at                TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by                VARCHAR2(64)  DEFAULT 'system' NOT NULL,
    trace_id                  VARCHAR2(128),
    CONSTRAINT uk_followup_event_id UNIQUE (event_id)
);

CREATE INDEX idx_followup_event_plan ON followup_event (tenant_id, plan_id);
CREATE INDEX idx_followup_event_type ON followup_event (tenant_id, event_type);

COMMENT ON TABLE followup_plan IS '随访计划';
COMMENT ON COLUMN followup_plan.plan_id IS '计划唯一ID';
COMMENT ON COLUMN followup_plan.tenant_id IS '租户ID';
COMMENT ON COLUMN followup_plan.patient_id IS '患者ID';
COMMENT ON COLUMN followup_plan.encounter_id IS '就诊记录ID';
COMMENT ON COLUMN followup_plan.pathway_id IS '关联临床路径ID';
COMMENT ON COLUMN followup_plan.disease_code IS '疾病编码';
COMMENT ON COLUMN followup_plan.risk_level IS '风险等级';
COMMENT ON COLUMN followup_plan.status IS '状态(DRAFT,ACTIVE,COMPLETED,CANCELLED)';
COMMENT ON COLUMN followup_plan.trace_id IS '追踪ID';

COMMENT ON TABLE followup_task IS '随访任务';
COMMENT ON COLUMN followup_task.task_id IS '任务唯一ID';
COMMENT ON COLUMN followup_task.plan_id IS '所属计划ID';
COMMENT ON COLUMN followup_task.task_type IS '任务类型(QUESTIONNAIRE,EXAM,LAB,OUTPATIENT)';
COMMENT ON COLUMN followup_task.due_date IS '执行期限';
COMMENT ON COLUMN followup_task.status IS '状态(PENDING,COMPLETED,OVERDUE,CANCELLED)';
COMMENT ON COLUMN followup_task.executor_id IS '执行人ID';
COMMENT ON COLUMN followup_task.executor_type IS '执行人类型(DOCTOR,NURSE,SYSTEM)';

COMMENT ON TABLE followup_questionnaire IS '随访问卷';
COMMENT ON COLUMN followup_questionnaire.questionnaire_id IS '问卷唯一ID';
COMMENT ON COLUMN followup_questionnaire.task_id IS '关联任务ID';
COMMENT ON COLUMN followup_questionnaire.form_data IS '表单数据(JSON)';
COMMENT ON COLUMN followup_questionnaire.score IS '评分结果';

COMMENT ON TABLE followup_event IS '随访异常事件';
COMMENT ON COLUMN followup_event.event_id IS '事件唯一ID';
COMMENT ON COLUMN followup_event.event_type IS '事件类型(ABNORMAL_RETURN,RESULT_INFLOW)';
COMMENT ON COLUMN followup_event.payload IS '事件载荷数据(JSON)';
COMMENT ON COLUMN followup_event.triggered_by IS '触发方';
