-- MedKernel v1.0 GA · GA-ENG-API-13 大规模列表 API（DM）

CREATE TABLE large_list_export_job (
    id                        NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id                    VARCHAR2(64)   NOT NULL,
    tenant_id                 VARCHAR2(64)   NOT NULL,
    resource_type             VARCHAR2(64)   NOT NULL,
    filter_criteria           CLOB           NULL,
    status                    VARCHAR2(32)   DEFAULT 'PENDING' NOT NULL,
    file_name                 VARCHAR2(255)  NULL,
    file_path                 VARCHAR2(512)  NULL,
    file_size                 NUMBER(19)     DEFAULT 0 NOT NULL,
    error_message             VARCHAR2(512)  NULL,
    time_cost_ms              NUMBER(19)     DEFAULT 0 NOT NULL,
    trace_id                  VARCHAR2(128)  NULL,
    created_at                TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by                VARCHAR2(64)   DEFAULT 'system' NOT NULL,
    updated_at                TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by                VARCHAR2(64)   DEFAULT 'system' NOT NULL,
    CONSTRAINT uk_large_list_job UNIQUE (job_id)
);

CREATE INDEX idx_large_list_job_tenant ON large_list_export_job (tenant_id, resource_type);

COMMENT ON TABLE large_list_export_job IS '大规模数据异步导出任务表';
COMMENT ON COLUMN large_list_export_job.id IS '自增主键';
COMMENT ON COLUMN large_list_export_job.job_id IS '异步导出任务全局唯一ID';
COMMENT ON COLUMN large_list_export_job.tenant_id IS '租户ID';
COMMENT ON COLUMN large_list_export_job.resource_type IS '导出的列表资源类型(如AUDIT_LOG等)';
COMMENT ON COLUMN large_list_export_job.filter_criteria IS '导出时提交的过滤筛选条件Json结构';
COMMENT ON COLUMN large_list_export_job.status IS '任务状态(PENDING,RUNNING,SUCCESS,FAILED)';
COMMENT ON COLUMN large_list_export_job.file_name IS '导出的物理文件名称';
COMMENT ON COLUMN large_list_export_job.file_path IS '物理存储路径或文件相对Key';
COMMENT ON COLUMN large_list_export_job.file_size IS '文件大小(字节)';
COMMENT ON COLUMN large_list_export_job.error_message IS '失败时存储的错误堆栈或异常描述';
COMMENT ON COLUMN large_list_export_job.time_cost_ms IS '导出耗时(毫秒)';
COMMENT ON COLUMN large_list_export_job.trace_id IS '请求链路追踪ID';
COMMENT ON COLUMN large_list_export_job.created_at IS '创建时间';
COMMENT ON COLUMN large_list_export_job.created_by IS '创建人账户或系统标识';
COMMENT ON COLUMN large_list_export_job.updated_at IS '最后更新时间';
COMMENT ON COLUMN large_list_export_job.updated_by IS '最后修改人账户或系统标识';
