-- MedKernel v1.0 GA · GA-SVC-PILOT-01 租户定制与客户成功多维生命周期（DM）

CREATE TABLE tenant_branding (
    id                  NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id           VARCHAR2(64)   NOT NULL,
    hospital_name       VARCHAR2(128)  NOT NULL,
    logo_url            VARCHAR2(512)  NULL,
    theme_color         VARCHAR2(32)   NULL,
    expert_mode         NUMBER(1)      DEFAULT 0 NOT NULL,
    custom_branding_json VARCHAR2(4000) NULL,
    created_at          TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by          VARCHAR2(64)   DEFAULT 'system' NOT NULL,
    updated_at          TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by          VARCHAR2(64)   DEFAULT 'system' NOT NULL,
    CONSTRAINT uk_tenant_branding UNIQUE (tenant_id)
);

CREATE TABLE tenant_success_plan (
    id                  NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id           VARCHAR2(64)   NOT NULL,
    current_stage       VARCHAR2(32)   NOT NULL,
    health_score        NUMBER(9)      DEFAULT 80 NOT NULL,
    activated_modules   VARCHAR2(512)  NULL,
    activated_pathways  VARCHAR2(512)  NULL,
    created_at          TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by          VARCHAR2(64)   DEFAULT 'system' NOT NULL,
    updated_at          TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by          VARCHAR2(64)   DEFAULT 'system' NOT NULL,
    CONSTRAINT uk_tenant_success_plan UNIQUE (tenant_id)
);

COMMENT ON TABLE tenant_branding IS '租户定制品牌信息表';
COMMENT ON COLUMN tenant_branding.id IS '自增物理主键';
COMMENT ON COLUMN tenant_branding.tenant_id IS '租户 ID';
COMMENT ON COLUMN tenant_branding.hospital_name IS '医院物理名称';
COMMENT ON COLUMN tenant_branding.logo_url IS '医院定制 Logo URL';
COMMENT ON COLUMN tenant_branding.theme_color IS '平台定制 UI 主题色';
COMMENT ON COLUMN tenant_branding.expert_mode IS '是否开启专家模式 (0-否, 1-是)';
COMMENT ON COLUMN tenant_branding.custom_branding_json IS '其他扩展样式的品牌 JSON 配置';
COMMENT ON COLUMN tenant_branding.created_at IS '创建时间点';
COMMENT ON COLUMN tenant_branding.created_by IS '创建人';
COMMENT ON COLUMN tenant_branding.updated_at IS '最后更新时间点';
COMMENT ON COLUMN tenant_branding.updated_by IS '最后更新人';

COMMENT ON TABLE tenant_success_plan IS '租户客户成功多维生命周期计划表';
COMMENT ON COLUMN tenant_success_plan.id IS '自增物理主键';
COMMENT ON COLUMN tenant_success_plan.tenant_id IS '租户 ID';
COMMENT ON COLUMN tenant_success_plan.current_stage IS '当前生命周期阶段 (PREPARATION, PILOT, ACCEPTANCE, PROMOTION, RUNNING, RENEWAL)';
COMMENT ON COLUMN tenant_success_plan.health_score IS '多维治理健康度评分';
COMMENT ON COLUMN tenant_success_plan.activated_modules IS '已激活系统服务模块逗号分隔列表';
COMMENT ON COLUMN tenant_success_plan.activated_pathways IS '已激活临床专病包逗号分隔列表';
COMMENT ON COLUMN tenant_success_plan.created_at IS '创建时间点';
COMMENT ON COLUMN tenant_success_plan.created_by IS '创建人';
COMMENT ON COLUMN tenant_success_plan.updated_at IS '最后更新时间点';
COMMENT ON COLUMN tenant_success_plan.updated_by IS '最后更新人';
