-- MedKernel v1.0 GA · V26 平台自建身份凭证表（达梦 DM8）
CREATE TABLE platform_credential (
    id              NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    credential_id   VARCHAR2(64)  NOT NULL,
    tenant_id       VARCHAR2(64)  NOT NULL,
    user_id         VARCHAR2(128) NOT NULL,
    username        VARCHAR2(128) NOT NULL,
    password_hash   VARCHAR2(100) NOT NULL,
    status          VARCHAR2(16)  DEFAULT 'ACTIVE' NOT NULL,
    must_change_pwd CHAR(1)       DEFAULT 'Y' NOT NULL,
    mfa_secret      VARCHAR2(128),
    created_at      TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by      VARCHAR2(64)  DEFAULT 'system' NOT NULL,
    updated_at      TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by      VARCHAR2(64)  DEFAULT 'system' NOT NULL,
    trace_id        VARCHAR2(64),
    CONSTRAINT uk_platform_credential_id UNIQUE (credential_id),
    CONSTRAINT uk_platform_credential_username UNIQUE (tenant_id, username),
    CONSTRAINT ck_platform_credential_status CHECK (status IN ('ACTIVE','DISABLED','LOCKED')),
    CONSTRAINT ck_platform_credential_mustchg CHECK (must_change_pwd IN ('Y','N'))
);

CREATE INDEX idx_platform_credential_login ON platform_credential (tenant_id, username, status);

COMMENT ON TABLE platform_credential IS '平台自建身份凭证表（外网 SaaS / 本地 dev 登录）';
