package com.medkernel.shared.api;

import java.util.List;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;
import com.medkernel.shared.api.error.ErrorCode;
import com.medkernel.shared.context.OrgScope;
import com.medkernel.shared.context.RequestContext;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * ApiResult 序列化契约测试 — 锁定对外 JSON 形态。
 * 任何字段重命名、删除都会让本测试失败，迫使做出兼容性决策。
 */
class ApiResultTest {

    private final ObjectMapper mapper = new ObjectMapper().registerModule(new JavaTimeModule());

    @AfterEach
    void clear() {
        RequestContext.clear();
    }

    @Test
    void okEnvelopeContainsRequiredFields() throws Exception {
        RequestContext.restore(new RequestContext.Snapshot("trace-abc", OrgScope.tenant("t-1"), "u-1"));

        ApiResult<String> result = ApiResult.ok("hello");
        JsonNode node = mapper.valueToTree(result);

        assertThat(node.get("success").asBoolean()).isTrue();
        assertThat(node.get("code").asText()).isEqualTo("OK");
        assertThat(node.get("message").asText()).isEqualTo("操作成功");
        assertThat(node.get("data").asText()).isEqualTo("hello");
        assertThat(node.get("traceId").asText()).isEqualTo("trace-abc");
        assertThat(node.get("timestamp").asText()).isNotBlank();
        assertThat(node.has("errors")).isFalse(); // NON_NULL — empty errors must not appear
    }

    @Test
    void errorEnvelopePropagatesCode() throws Exception {
        RequestContext.restore(new RequestContext.Snapshot("trace-err", OrgScope.empty(), null));

        ApiResult<Void> result = ApiResult.error(ErrorCode.NOT_FOUND, "患者不存在");
        JsonNode node = mapper.valueToTree(result);

        assertThat(node.get("success").asBoolean()).isFalse();
        assertThat(node.get("code").asText()).isEqualTo("ENG-API-005");
        assertThat(node.get("message").asText()).isEqualTo("患者不存在");
        assertThat(node.has("data")).isFalse();
        assertThat(node.get("traceId").asText()).isEqualTo("trace-err");
    }

    @Test
    void errorEnvelopeWithFieldErrorsIsSerialized() throws Exception {
        RequestContext.restore(new RequestContext.Snapshot("trace-v", OrgScope.empty(), null));

        List<ApiError> errors = List.of(
            new ApiError("patientMpi", "NotBlank", "患者主索引必填"),
            new ApiError("severity", "Pattern", "严重级别取值不在白名单内")
        );
        ApiResult<Void> result = ApiResult.error(ErrorCode.VALIDATION_FAILED, "请求参数校验失败", errors);
        JsonNode node = mapper.valueToTree(result);

        assertThat(node.get("success").asBoolean()).isFalse();
        assertThat(node.get("code").asText()).isEqualTo("ENG-API-002");
        assertThat(node.get("errors")).hasSize(2);
        assertThat(node.get("errors").get(0).get("field").asText()).isEqualTo("patientMpi");
        assertThat(node.get("errors").get(1).get("code").asText()).isEqualTo("Pattern");
    }

    @Test
    void traceIdAutoGeneratedWhenContextEmpty() {
        RequestContext.clear();
        ApiResult<String> result = ApiResult.ok("x");
        assertThat(result.traceId()).isNull();
    }
}
